### ISSUE TITLE
a second goes 2x slower on laggy devices.

### ISSUE THREAD

**Issue by WolfPlayzRx** [OpenNBS/OpenNoteBlockStudio#257]
i just use noteblock studio in my old laptop since my pc is broken when i was first using it in my old laptop i knew something was different  i look at the **tick per second is slowing down** due to **lag**. its different from my fast pc, Pls fix it i know u have alot of stuff to do but pls fix it its my fav software. Goodluck, pls fix it asap! it would help laggy people.

**Comment by MericGit** [comment]
Could you clarify what you mean by tick per second? 

Anyway, program performance doesn't really have an easy fix. It's an ongoing goal for sure.
Are you lagging during song playback? In which case you can always try closing background programs such as your web browser, any games, etc. 

While NBS does occasionally have performance issues, performance is usually still fine (even on my crappy laptop from 2012), so I'd double check if you have any CPU-intensive programs in the background. 

There's a python port in the works as well that may possibly improve performance since it would no longer be GML.

**Comment by WolfPlayzRx** [comment]
sorry for a slow reply, but I did everything to fix the lag on my old laptop, close the background apps, exit programs, and even boost my drive and everything it still wont fix it. sometimes the tick goes fast then it goes slow. but thank you for Advice.

**Comment by TheDarknez** [comment]
wait we have the same problem i just recently send the issue

**Comment by chenxi050402** [comment]
Can you use software like MSI Afterburner of Fraps to check the FPS when you're using the software?
The current anti-slowdown method is to adjust the timing measured in the last frame and it will cause unstable playback if the FPS is low.

**Comment by Bentroen** [comment]
The player mode added in 3.9.0 should make it possible to at least hear songs.

In terms of general performance, there's not much we can do as GameMaker draws everything to the screen every frame (even static stuff that's not being updated, like windows). This, as @MericGit said above, can only be fixed by moving to a proper GUI framework.
