### ISSUE TITLE
About resources pack

### ISSUE THREAD

**Issue by lonely-nightmare** [OpenNBS/OpenNoteBlockStudio#260]
There is no official resources pack for higher notes except those 25 notes

**Comment by chenxi050402** [comment]
If you meant for **Datapacks**, you can click the "Get extra notes pack" button in the export datapack window;
I you meant for note blocks in the game, you can only achieve that using a **mod**.
Another way to do that in the game is to use the extra notes pack and use **command blocks** to play the extended sounds.

**Comment by lonely-nightmare** [comment]
Extra notes pack only Support a Song
I mean is there a resource pack that has all the instruments and notes at the same time

**Comment by chenxi050402** [comment]
There are only resource packs for extending the range for one instrument like harp or piano.
The extra notes pack includes all instruments and notes, but you can only use them in /playsound commands.
As far as I know, there are no mods about extending note block ranges since it requires changing how sounds in Minecraft works.
