### ISSUE TITLE
OpenNBS Shows White Screen on Startup

### ISSUE THREAD

**Issue by CreeperPookie** [OpenNBS/OpenNoteBlockStudio#267]
**Is your feature request related to a problem? Please describe.**
Something I've noticed is that whenever I open an OpenNBS window for the first time, it shows a fully white screen. Now in light mode, this makes perfect sense; but in Dark / Fluent Dark mode, it's quite unexpected.

**Describe the enhancement you'd like**
Personally, I think this pre-screen should be either based on the theme the user selects, (i.e. black/gray for dark mode, white for light mode) or be a darker color for all settings. However, I do understand that the white screen could be a limitation of the GameMaker Language and might not be changeable.

**Comment by chenxi050402** [comment]
Yes, as you said, the white screen is not changeable because the code can't change the splash screen color, so there's no easy way to fix this issue.
But it's fixable in 4.0 since it's gonna be in Python instead of GML.

**Comment by Bentroen** [comment]
Yes, this is a low-level issue as you pointed out.
This also happens when NBS is stuck in a long operation (e.g. exporting a data pack or MP3 file), as GameMaker completely stops drawing to the screen while it's processing. The [screen_refresh](https://yellowafterlife.itch.io/screen-refresh) extension used to provide a workaround, but it's since no longer working.

**Comment by Bentroen** [comment]
Closing as there's not much we can do about this.
