### ISSUE TITLE
Custom Instruments don't export

### ISSUE THREAD

**Issue by Bumper3241** [OpenNBS/OpenNoteBlockStudio#286]
**Describe the bug**
Custom instruments don't export to MP3 when selected, and the spots where they are supposed to be are silent

**To Reproduce**
1. Import a custom instrument
2. Set it anywhere in the song
3. select "Export as MP3"

**Expected behavior**
The previous version I used, all custom instruments were included in the MP3 export

**Screenshots**
They don't explain the issue

**Additional context**
It's not an issue with the sound file, as it plays just fine in the editor. it's only when exporting that it is messed up.

**Comment by Bentroen** [comment]
Hi! Custom instruments are being exported just fine for me. Have you checked that the files are still in their original locations by the time you export the song?

If you go to 'Instrument settings', Note Block Studio will display the sound file name in red if it can't load the sound. However, if you move or delete the file from its original location, it will keep displaying it as normal (because the sound is already loaded into memory), but the MP3 export code will ignore it since it cannot be found.

**Comment by Bentroen** [comment]
Hey, are you still experiencing this issue?
