### ISSUE TITLE
Can't open V3.9.1

### ISSUE THREAD

**Issue by gueli844** [OpenNBS/OpenNoteBlockStudio#289]
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_controller:

Trying to draw non-existing sprite.
at gml_Script_wallpaper_init
############################################################################################
gml_Script_wallpaper_init (line -1)
gml_Script_change_theme
gml_Script_control_create
gml_Object_obj_controller_Create_0 (line -1)

**Comment by Bentroen** [comment]
Hi! Please go to the program's data folder (usually `C:\Users\<username>\Minecraft Note Block Studio\Data`), then delete `wallpaper.bat` and `Wallpaper.jpg`. Restart NBS. If the issue persists, go to `C:\Users\<username>\AppData\Roaming\Minecraft_Note_Block_Studio`, open `settings.ini` and change the line that says `acrylic="1"` to `acrylic="0"`. This will disable transparency effects, which should prevent this issue from occurring.
I'm sorry for the highly technical explanation! We're still investigating some issues with the way the program creates the blurred background for the Acrylic effect. Feel free to leave a comment if you have any trouble getting it to work. ;)

**Comment by gueli844** [comment]
Hey, thanks a lot for the response!
I can't seem to find acrylic="1" on my settings. Should I add it in?

**Comment by Bentroen** [comment]
Hmm, since you don't have this line on the settings file, you have probably updated from a version older than 3.9.0. I'm not quite sure, but this could be related to the crash in some way. I'll investigate!

> I can't seem to find acrylic="1" on my settings. Should I add it in?
Actually, this setting is _enabled_ by default and it's the one causing this issue, so if you add `acrylic="0"` the program won't try to run the code that's causing it. Just make sure to add it under the section that says `[preferences]`, or else it's not gonna work.

**Comment by Bentroen** [comment]
Hey, are you still experiencing this issue?

**Comment by gueli844** [comment]
Hey, sorry for the late response. This did indeed worked, thanks a lot! :D

**Comment by Bentroen** [comment]
Glad to know this! :D

I'll close the issue now, feel free to leave a comment if you need anything else.
