### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by hackerplayz124** [OpenNBS/OpenNoteBlockStudio#295]
how can uninstall this program so i can download better version

- [ ] resolved

**Comment by Bentroen** [comment]
Hello! You can uninstall NBS just like you do it for any other program. There are a couple ways to do it:

1) Open the Start Menu, click the 'All Apps' button, look for a folder named 'Minecraft Note Block Studio', and then open the 'Uninstall' icon located inside it.
![image](https://user-images.githubusercontent.com/29354120/145911044-cbfc72e4-8b57-4302-9e4d-2c82a6e3e858.png)

2) Open the Control Panel, click 'Programs and Features', look for 'Minecraft Note Block Studio' and click 'Uninstall'.
![image](https://user-images.githubusercontent.com/29354120/145911439-7dba9dce-ab86-4bc4-aae2-7b6607428dd5.png)

Keep in mind that, in general, you don't need to uninstall previous versions in order to install a newer one -- you can just run the newer version's installer and it will replace all relevant files automatically.

**Comment by hackerplayz124** [comment]
ok keep up the work

**Comment by hackerplayz124** [comment]
bye
