### ISSUE TITLE
rezise icons don't work/get overriden

### ISSUE THREAD

**Issue by BartTerpstra1** [OpenNBS/OpenNoteBlockStudio#305]
**Describe the bug**
hovering over the edge of the program causes the mouse cursor to flicker the rezise mouse pointer, coming to rest on the regular mouse pointer.

this makes it seem to the user that the band to resize the window is 0 pixels, but when you left click with the regular mouse icon, the window does get resized and the mouse gets the appropriate icon.

this resize operation freezes all other operations?

**To Reproduce**
1. open Open NBS
2. have it in the middle of the screen, about 1/3 -1/5 the size of the screen
3. try to hover over the edge of the program and get it to rest on the rezise mouse cursor (usually: <->)
    3a. be unable to do so
4. left click where it should happen
   4.a. notice you can resize the window.

**Expected behavior**
if you hover over the edge of the window, it should rest on the resize icon if the mouse cursor could resize the window if it were to left-click there.

**Additional context**
windows 10.
Amd radeon integrated graphics.
Ryzen 5 CPU.
fresh install, latest version: 3.9.3

**Comment by Bentroen** [comment]
Hi, and thank you for your detailed report!

This is an issue with GameMaker, the engine that Note Block Studio is built on. Due to some internal limitations, resizing a window causes the game's logic to freeze. There's not much we can do about that -- if you resize the window while playing a song, you'll notice the playback freezes as well. The same applies to the cursor flickering when you hover the edge of the window -- without coding an extension that modifies GameMaker's behavior, there's nothing we can do to override it.

It's possible to make it at least look a bit nicer using [this free extension](https://yellowafterlife.itch.io/gamemaker-window-resize-fix), but I'm not too fond of adding yet another dependency just to fix this -- after all, resizing works properly and it's just a minor inconvenience.

**Comment by BartTerpstra1** [comment]
very fair.
I agree with your conclussions.
*grumbles at gamemaker*
