### ISSUE TITLE
Wrong instrument blocks when exporting branch schematic

### ISSUE THREAD

**Issue by ExtraLines** [OpenNBS/OpenNoteBlockStudio#313]
**The Bug**
When pasting the branch schematic into minecraft, the block under the note block is not what it's supposed to be, i.e. glass under a note block that's supposed to be a snare drum.

**To Reproduce**
1. Create a melody of note blocks in nbs.
2. Export that line of notes as a branch schematic. (In this case let all have default blocks under the instruments)
3. Paste the schematic into minecraft 1.12 (or any other version) using world edit.

**Expected behavior**
Suppose we have a line of note blocks in nbs written like this:
![c11](https://user-images.githubusercontent.com/59631889/157129901-c0328f2a-d1c5-4746-8fe0-82eed1bc2889.PNG)
Note that the very left is harp, the very right is pling, and everything else is in order.
Here are the blocks for the instruments:
![c22](https://user-images.githubusercontent.com/59631889/157129942-dfb36ee9-816c-4523-9244-073fb7f853d8.PNG)
Here is the result when it is exported as a schematic into minecraft 1.12 using world edit:
![2022-03-07_17 26 58](https://user-images.githubusercontent.com/59631889/157130361-18be11ac-6814-4cd9-812b-da45226982d6.png)
The very left block should be dirt, the next should be wood planks, and the very right should be glowstone. However, everything is shifted one to the left and the very right block is stone for some reason instead of dirt if we were to shift everything. I know that this is not a world edit issue because I tried it on multiple versions (1.12 and 1.17) and it wouldn't be a block id issue within world edit because the circuitry is correct and all the blocks above are indeed instrument blocks.

Please look into it if possible, thanks.

**Comment by Bentroen** [comment]
The block ID gets retrieved and set in this line:

https://github.com/OpenNBS/OpenNoteBlockStudio/blob/d6bc64923943b4d18f868a860b0d6db9821952d4/scripts/branch_export/branch_export.gml#L104

But the actual problem is here:

https://github.com/OpenNBS/OpenNoteBlockStudio/blob/d6bc64923943b4d18f868a860b0d6db9821952d4/scripts/branch_export/branch_export.gml#L75

This is using a not-so-appropriate method, relying on the object handle, to find the instrument index. A better (and correct) way would be as is being done on the data pack visualizer:

https://github.com/OpenNBS/OpenNoteBlockStudio/blob/d6bc64923943b4d18f868a860b0d6db9821952d4/scripts/dat_generate/dat_generate.gml#L37
