### ISSUE TITLE
Lower pitch notes

### ISSUE THREAD

**Issue by nucleartoast999** [OpenNBS/OpenNoteBlockStudio#358]
Since the new update came out, base note pitches are now higher which personally I don't like, because it changes the tone of a song. I request that base note pitches are reverted to the way they were in 3.9.3 .

**Comment by Bentroen** [comment]
This is intended, so I'm sorry it can't be added! The pitch calculation was just plain wrong in versions up to 3.9.3, causing pitch to be off by about ±10 cents for every octave up or down from the original pitch of a note, compared to equal-tempered tuning (see #317 for a detailed write-up on this issue).

That's why lower notes sound higher: they actually _are_ higher, but it's just that your ears are used to the weird tuning used by NBS before this update. I know it sounds weird, but bear with me, this is actually the way it should be. It's just a matter of getting used to the new (and accurate) tuning :)
