### ISSUE TITLE
When exported as Schematic noteblocks are not loading in.

### ISSUE THREAD

**Issue by ajaymds** [OpenNBS/OpenNoteBlockStudio#398]
When I click export as Schematic, and choose my desired settings, I load my schematic into my Minecraft world, and everything loaded except the noteblocks.

**To Reproduce**
1. Go to 'Open note block studio'
2. Click on 'export as Schematic'
3. Choose these settings, simple walkway, 1.13+, 30 repeaters per row, compress layers, and 10 tics per second.
4. Load in Minecraft, and everything loaded except noteblocks 

**Expected behavior**
The noteblocks were supposed to load but they didn't

By the way, it might be cubial.xyz's fault because I had to convert it to. schematic, and I was using the latest version of java.

**Comment by Bentroen** [comment]
Hi! The 1.13+ export option exports a `.nbt` file, meant to be used with vanilla structure blocks. If you'd like to export as a regular `.schematic`, please choose the 1.11-1.12 option (keep in mind you can only import it in versions up to 1.12 or else all note blocks will have the same instrument, due to a change in how note blocks are stored internally in the world in 1.13).

**Comment by ajaymds** [comment]
Tysm! This really helps out a ton!

**Comment by ajaymds** [comment]
Tysm! This really helps out a ton!
