### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by stinkyxylene** [OpenNBS/OpenNoteBlockStudio#399]
I opened NBS studio and loaded one of the saved songs, "Megalovanis", and no sound came out. My PC and speaker didn't have a problem, + I just opened the app, so I didn't touch anything to mute the whole sound. I even restarted the PC. 

Could this be a bug? if yes, how can I fix this problem?

**Comment by Bentroen** [comment]
This usually happens when you connect or disconnect an audio device, such as headphones or speakers. Usually, restarting NBS fixes this problem.

If you still can't hear NBS, right-click the speaker icon on the Windows taskbar and click 'Sounds'. On the window that opens, go to the _'Playback devices'_ tab. Right-click the audio device that you want to use NBS with and click _'Set as default device.'_ (If it's already the default, you don't need to change anything.). Then, restart NBS and the sound should be back.

Hope this helps! If you still have issues, please leave a comment.
