### ISSUE TITLE
Not Properly Fitting Window

### ISSUE THREAD

**Issue by AgenTherian** [OpenNBS/OpenNoteBlockStudio#401]
When I open NoteBlockStudio, the window opens up, however everything seems enlarged. There has been another time on a different computer where everything was too small. I don't know if there is a feature where you can change this or not. If there is it really isn't obvious. Another thing, when I click the compatibility to fix it, it opens up just fine, but I'm not able to close out of it. There is no X button and it doesn't do anything when I click outside of the popup.

![noteblockstudiobug](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/135302270/24a9be16-73de-4e92-8d7c-b45d51ed0603)

**Comment by Bentroen** [comment]
By default, the UI scale follows your DPI setting on Windows, which you can access by going to _Settings > System > Screen > Adjust scale and layout > Change size of text, apps and other items`_. The window looks "bigger" because your Windows scale setting is larger than 100%. On the computer where it all looks small, you must have it set to 100% but in a large resolution — is that correct? :)

You can override this setting in NBS by going to _Settings > Preferences > Interface > Window > Scale_, then click and drag the number to increase or decrease it. Keep in mind the 'Reset' button will make it the value it was before, since, again, we use your Windows UI scaling setting for determining a suitable default window scale. Hope this helps!
