### ISSUE TITLE
it is failing to install 

### ISSUE THREAD

**Issue by pat600130** [OpenNBS/OpenNoteBlockStudio#471]
so when i run the "Minecraft.Note.Block.Studio" exe 
first launch i give admin then
![Screenshot (69)](https://github.com/user-attachments/assets/3ae0c2a8-a907-42e7-813f-3727c67b34cf)

upon relaunch it asks for admin as normal BUT when i accept it seams as normal then  it asks again and i accept and AGAIN it asks then i accept a third time and it "can not accept control messages at this time"
![Screenshot (68)](https://github.com/user-attachments/assets/758d0b57-9d8d-4fab-9c2d-38ec9f11fbc4)

i have no clue what could be causing this

**Comment by Bentroen** [comment]
This seems like something specific to your operating system, such as misconfigured permissions. There's not much we can do about this at this time! Although you may try [downloading a ZIP](https://github.com/OpenNBS/OpenNoteBlockStudio/releases) instead of an executable installer, which doesn't require running an installation process.
