### ISSUE TITLE
Option to reduce MP3 export dialogue.

### ISSUE THREAD

**Issue by Encode42** [OpenNBS/OpenNoteBlockStudio#76]
The MP3 export dialog makes exporting as MP3 a bit more cumbersome.

The locked layers box should automatically close after you export. I keep trying to open a new file, but that box is still open, preventing me from doing so. It adds additional strain to go back and forth, clicking multiple buttons.
Another issue I found is with the dialog after the export. There should be an option in the preferences to suppress the "Do you want to open?" dialogue box. I rarely want to open the MP3, so clicking "No" really makes it take longer.

A section in the preferences to disable all dialogue when exporting MP3 or other features would be nice.

EDIT: Maybe there could be another option to set whether or not to include locked layers globally? So that you don't keep having to enable/disable it.

**Comment by Bentroen** [comment]
I know this issue has been sitting here for a while, being juggled between milestones. Sorry for not addressing it earlier!

While I do think you raise a valid point (exporting multiple MP3s is kinda cumbersome as the export process currently stands), I also believe that, in order for the amount of clicks you'd save to be meaningful at all, you'd have to export _hundreds_ of MP3s — please correct me if I'm wrong. 

The few necessary actions are intrinsic for the export process to work, and while it's possible to reduce the overall number of clicks per export, the difference would be negligible for _almost_ everyone, which doesn't justify adding more toggles to the preferences.

> The locked layers box should automatically close after you export.

This would be inconsistent with the datapack and schematic exports, in which the window remains open in case you want to tweak some settings after exporting. Though I understand that there's nothing in that window for you to tweak, so in this case it might make sense to close it.

> There should be an option in the preferences to suppress the "Do you want to open?" dialogue box. I rarely want to open the MP3, so clicking "No" really makes it take longer.

The dialogue is there just to make it more convenient to jump straight to the end result after exporting, which is what most users would want – the 'No' option is there for everyone else. It's commonplace in many programs that generate files and I honestly don't see a reason to remove it. Adding a toggle to the preferences is possible, but it's overkill for such a small thing and would result in more bloat.

> Maybe there could be another option to set whether or not to include locked layers globally? So that you don't keep having to enable/disable it.

Again, this would be inconsistent with datapacks and schematics. Since they allow you to choose the settings prior to exporting the file, turning the locked layers into a global preference wouldn't make much sense.

I do understand that the small number of clicks pile up when you're exporting dozens of files – but at the point it makes a _significant_ difference, you'd be better off automating the process using external tools such as `pynbs`. We are working on more tools that will make it easier to handle multiple files in the future, for cases like these in which NBS falls short.

I'm sorry if that was not what you expected to hear, thoughh feel free to suggest or add anything else I might have missed. :)

**Comment by Encode42** [comment]
The audio export process in the new betas supersedes this issue.
